import { useCharacterStore } from "../stores/character.store";
import { Ring } from "./ring";

export function Rings() {
  const {
    airValue,
    updateAirValue,
    earthValue,
    updateEarthValue,
    fireValue,
    updateFireValue,
    waterValue,
    updateWaterValue,
    voidValue,
    updateVoidValue,
  } = useCharacterStore();

  return (
    <div
      className={`
        relative
        h-[230px]
        w-[230px]
      `}
    >
      <Ring
        value={airValue}
        setValue={updateAirValue}
        ringType="air"
        className={`
          absolute
          top-0
          right-8
        `}
        labelClassName={`
          absolute
          bottom-2
          -right-10
        `}
        inputClassName={`
          absolute
          -bottom-3
          left-0
        `}
      />
      <Ring
        value={earthValue}
        setValue={updateEarthValue}
        ringType="earth"
        className={`
          absolute
          top-0
          left-8
        `}
        labelClassName={`
          absolute
          bottom-2
          -left-14
        `}
        inputClassName={`
          absolute
          -bottom-3
          right-0
        `}
      />
      <Ring
        value={fireValue}
        setValue={updateFireValue}
        ringType="fire"
        className={`
          absolute
          top-20
          right-2
        `}
        labelClassName={`
          absolute
          -bottom-5
          right-3
        `}
        inputClassName={`
          absolute
          top-3
          -left-3
        `}
      />
      <Ring
        value={waterValue}
        setValue={updateWaterValue}
        ringType="water"
        className={`
          absolute
          top-20
          left-2
        `}
        labelClassName={`
          absolute
          -bottom-5
          left-2
        `}
        inputClassName={`
          absolute
          top-3
          -right-3
        `}
      />
      <Ring
        value={voidValue}
        setValue={updateVoidValue}
        ringType="void"
        className={`
          absolute
          top-32
          left-19
        `}
        labelClassName={`
          absolute
          -bottom-5
          left-4
        `}
        inputClassName={`
          absolute
          -top-3
          left-5
        `}
      />
    </div>
  );
}
